WORKERS: 4

MODEL:
  NAME: cls_cvt
  SPEC:
    INIT: 'trunc_norm'
    NUM_STAGES: 3
    PATCH_SIZE: [7, 3, 3]
    PATCH_STRIDE: [4, 2, 2]
    PATCH_PADDING: [2, 1, 1]
    DIM_EMBED: [64, 192, 384]
    NUM_HEADS: [1, 3, 6]
    DEPTH: [1, 4, 16]
    MLP_RATIO: [4.0, 4.0, 4.0]
    ATTN_DROP_RATE: [0.0, 0.0, 0.0]
    DROP_RATE: [0.0, 0.0, 0.0]
    DROP_PATH_RATE: [0.0, 0.0, 0.1]
    QKV_BIAS: [True, True, True]
    CLS_TOKEN: [False, False, True]
    POS_EMBED: [False, False, False]
    QKV_PROJ_METHOD: ['dw_bn', 'dw_bn', 'dw_bn']
    KERNEL_QKV: [3, 3, 3]
    PADDING_KV: [1, 1, 1]
    STRIDE_KV: [2, 2, 2]
    PADDING_Q: [1, 1, 1]
    STRIDE_Q: [1, 1, 1]

TRAIN:
  OPTIMIZER: 'AdamW' 
  BATCH_SIZE: 64
  LR: 0.000125
  IMAGE_SIZE: [224, 224]
  BEGIN_EPOCH: 0
  END_EPOCH: 100
  WD: 0.05

  SCHEDULER:
    NAME: 'OneCycleLR'
    DIV_FACTOR: 25
    FINAL_DIV_FACTOR: 1e4
    WARMUP_EPOCHS: 1