WORKERS: 4

MODEL:
  NAME: cls_resnet18
  SPEC:
    INIT: 'kaiming'
    PRETRAINED: False
    DROP_RATE: 0.0

TRAIN:
  BATCH_SIZE: 128
  LR: 0.00025
  IMAGE_SIZE: [224, 224]
  BEGIN_EPOCH: 0
  END_EPOCH: 100
  WD: 0.05
  WARMUP_EPOCHS: 1  # Added for OneCycleLR