WORKERS: 4

MODEL:
  NAME: cls_vit
  SPEC:
    INIT: 'trunc_norm'
    PATCH_SIZE: 16
    EMBED_DIM: 768
    DEPTH: 12
    NUM_HEADS: 12
    DIM_HEAD: 64
    MLP_RATIO: 4.0
    POOL: 'cls'
    DROP_RATE: 0.0
    ATTN_DROP_RATE: 0.0
    DROP_PATH_RATE: 0.1

TRAIN:
  BATCH_SIZE: 64
  LR: 0.000125
  IMAGE_SIZE: [224, 224]
  BEGIN_EPOCH: 0
  END_EPOCH: 100
  WD: 0.05
  WARMUP_EPOCHS: 5